### PR TITLE
Fix recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by henryiii** [comment]
Looks good, but why is paramiko gone?

**Comment by ocefpaf** [comment]
> Looks good, but why is paramiko gone?

It is not declared as a dependency upstream. Maybe it was an optional one?

**Comment by henryiii** [comment]
Yes, it's optional. Usually optional deps are included on conda-forge if they are packaged and reasonably useful.

**Comment by ocefpaf** [comment]
Yep, the `ssh` option in https://github.com/tomerfiliba/plumbum/blob/v1.7.2/setup.cfg#L63

Should we make that "mandatory" here in the feedstock?

**Comment by henryiii** [comment]
Yes, I think it's fine to be required here (since there aren't simple optional deps, and ParamikoMachine is mostly better than the SshMachine).

**Comment by ocefpaf** [comment]
> Yes, it's optional. Usually optional deps are included on conda-forge if they are packaged and reasonably useful.

To be honest, as the person that kind of created that rule, I regret it :smile: The packages are getting bigger and folks are getting confused with the differences from PyPI and conda-forge. With that said, I'm all for non-disruptive changes. We had paramiko here, let's keep it!

**Comment by henryiii** [comment]
Yeah, not sure I'd argue to add it, but let's keep it, at least for now.

**Comment by henryiii** [comment]
Thanks!

**Pull request merged**
